spring:
  application:
    name: VkFriendsWeather

  profiles:
    active: env

  jpa:
    generate-ddl: true
    open-in-view: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/friends
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          vk:
            client-id: ${VK_CLIENT_ID}
            client-secret: ${VK_CLIENT_SECRET}
            redirect-uri: ${VK_REDIRECT_URL}
            authorization-grant-type: authorization_code
            client-authentication-method: post
            scope: email
            client-name: VK
            provider: vk
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get
            user-name-attribute: id

server:
  port: 8090

springdoc:
  api-docs:
    path: /api-docs

app:
  weather:
    apiKey: ${WEATHER_API_KEY}
    units: metric
    lang: ru